# Site settings
title: Beverly's Blog of Fun
email: bev@bev4sunnyvale.com
description: >
  Beverly is a software engineer. She cares a lot about animal rights. She also likes board games, vegan desserts, and kitties.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bev-a-tron.github.io" # the base hostname & protocol for your site
twitter_username: balau
github_username:  bev-a-tron 

# Build settings
markdown: kramdown
