# Site settings
title: Beverly's Blog of Fun
email: beverly@outlier.ai
description: >
  Beverly is a senior software engineer at Outlier AI. She cares a lot about social and economic justice and animal rights. She also likes hacking on stuff, board games, vegan desserts, and kitties.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://bev-a-tron.github.io" # the base hostname & protocol for your site
twitter_username: balau
github_username:  bev-a-tron 

# Build settings
markdown: kramdown
