# Site settings
title: Beverly's Blog of Fun
email: beverly@karmiclabs.com
description: >
  This is Beverly's blog of fun!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: balau
github_username:  bev-a-tron

# Build settings
markdown: kramdown
